### ISSUE TITLE
DateTimePicker issue

### ISSUE THREAD

**Issue by KUDANDOU** [nazimamin/HotelManagement#2]
I am facing a challenge if i try to log in using the admin credential..It throws a SystemAargument out of range exception Value of 12/20/2017 '12:00:00' is not valid for MinDate. MinDate must be less than MaxDate

**Comment by ElAngeluz** [comment]
change max value in 

![image](https://user-images.githubusercontent.com/10533576/34364318-9fd14b22-ea52-11e7-99bc-2e7ae878f4a7.png)

**Comment by nazimamin** [comment]
@KUDANDOU This was an Intro SWE project and I don't have access to a Windows machine. @ElAngeluz Yeap, or I think you can change [MaxDate and MinDate](https://github.com/nazimamin/HotelManagement/blob/d79b64d14f794f4fcae19b0cd32b9014966dd547/HotelManagement/Frontend.Designer.cs#L477). So set `MaxDate = new System.DateTime(2015, 4, 27, 23, 59, 0, 0)` to a year from now like `MaxDate = todayDate.AddYears(1)` and all the MinDate to today's date.

**Comment by KUDANDOU** [comment]
@nazimamin i dd resolve the error its now working.......also noticed the error of not sedning out smses to clients
