### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by NaheelSalman** [nazimamin/HotelManagement#4]
I'm Using it with:

- Visual Studio 2019
- MS SQL MANAGEMENT 2018

Help me if you can

**Comment by shads06** [comment]
@NaheelSalman  I used it with 

- Visual Studio 2013

- MS SQL Server Mgt. Studio 2014 

Although initially, it gave me some errors when I ran this application but I resolved those errors and the application worked.
Really nice application and I'm working on some enhancements as well.
There are still some more errors in this application I'm facing to run which I'm trying to solve.
